-- V11 — Estrutura comercial + certificados
-- 1) Funde Documentação Avançada no produto Documentação Imobiliária Profissional.
-- 2) Preserva aulas, testes, progresso e acessos.
-- 3) Cria certificados verificáveis.
begin;

-- Curso destino
update public.courses
set title='Documentação Imobiliária Profissional',
    slug='documentacao-imobiliaria-profissional',
    description='Due diligence documental aplicada à mediação imobiliária, com checklists, divergências, riscos e ferramenta profissional.'
where id=12;

-- Move módulos do antigo curso 3 para o curso 12, sem apagar aulas/progresso.
do $$
declare mx int;
begin
  select coalesce(max(position),0) into mx from public.modules where course_id=12;
  update public.modules
  set course_id=12, position=mx+position
  where course_id=3;
end $$;

-- Transfere acessos existentes do curso antigo para o novo.
insert into public.course_access(user_id,course_id,access_type,granted_at,expires_at,granted_by,notes)
select user_id,12,access_type,granted_at,expires_at,granted_by,
       coalesce(notes,'') || ' · Migrado de Documentação Avançada'
from public.course_access
where course_id=3
on conflict(user_id,course_id) do nothing;

-- Arquiva o produto antigo, mas não apaga o registo histórico.
update public.courses
set status='archived',
    title='Documentação Avançada · integrada',
    description='Conteúdo integrado em Documentação Imobiliária Profissional.'
where id=3;

create table if not exists public.certificates(
  id bigint generated by default as identity primary key,
  code text not null unique,
  user_id uuid not null references auth.users(id) on delete restrict,
  course_id bigint not null references public.courses(id) on delete restrict,
  issued_at timestamptz not null default now(),
  completed_at timestamptz not null default now(),
  final_score numeric(5,2),
  total_minutes integer not null default 0,
  status text not null default 'valid' check(status in ('valid','revoked')),
  revoked_at timestamptz,
  revoked_reason text,
  unique(user_id,course_id)
);

alter table public.certificates enable row level security;

drop policy if exists "users read own certificates" on public.certificates;
create policy "users read own certificates" on public.certificates
for select using(auth.uid()=user_id or public.is_admin());

drop policy if exists "admins manage certificates" on public.certificates;
create policy "admins manage certificates" on public.certificates
for all using(public.is_admin()) with check(public.is_admin());

-- Dados mínimos para validação pública; evita expor email.
create or replace view public.valid_certificates as
select ce.code,ce.status,ce.issued_at,ce.completed_at,ce.final_score,ce.total_minutes,
       p.full_name,c.title as course_title
from public.certificates ce
left join public.profiles p on p.id=ce.user_id
join public.courses c on c.id=ce.course_id
where ce.status='valid';

commit;

select id,title,slug,status from public.courses order by position nulls last,id;
