-- V12.1 — Analisar Imóvel · Due Diligence da Angariação
begin;

create table if not exists public.property_analyses(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  municipality text,
  property_type text not null,
  purpose text,
  answers jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  risk_level text not null default 'low' check(risk_level in ('low','medium','high')),
  status text not null default 'draft' check(status in ('draft','completed','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists property_analyses_user_idx
on public.property_analyses(user_id,updated_at desc);

alter table public.property_analyses enable row level security;

drop policy if exists "users read own property analyses" on public.property_analyses;
create policy "users read own property analyses" on public.property_analyses
for select using(auth.uid()=user_id or public.is_admin());

drop policy if exists "users create own property analyses" on public.property_analyses;
create policy "users create own property analyses" on public.property_analyses
for insert with check(auth.uid()=user_id);

drop policy if exists "users update own property analyses" on public.property_analyses;
create policy "users update own property analyses" on public.property_analyses
for update using(auth.uid()=user_id or public.is_admin())
with check(auth.uid()=user_id or public.is_admin());

drop policy if exists "users delete own property analyses" on public.property_analyses;
create policy "users delete own property analyses" on public.property_analyses
for delete using(auth.uid()=user_id or public.is_admin());

commit;
