-- V5.1 — Analisar Terreno
-- Incremental. Não elimina dados existentes.
begin;

create table if not exists public.land_analysis_rules(
  id bigint generated by default as identity primary key,
  rule_type text not null check(rule_type in ('checklist','alert','next_step')),
  category text not null,
  severity text not null default 'info' check(severity in ('info','baixo','medio','alto')),
  title text not null,
  message text not null,
  next_step text,
  conditions jsonb not null default '{}'::jsonb,
  position int not null default 100,
  verified_at date not null default date '2026-08-18',
  source_url text,
  status text not null default 'published'
);

create table if not exists public.land_analyses(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  municipality text,
  article text,
  objective text not null,
  answers jsonb not null default '{}'::jsonb,
  risk_level text,
  checklist jsonb not null default '[]'::jsonb,
  alerts jsonb not null default '[]'::jsonb,
  next_steps jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.land_analysis_rules enable row level security;
alter table public.land_analyses enable row level security;

drop policy if exists "published land rules readable" on public.land_analysis_rules;
create policy "published land rules readable" on public.land_analysis_rules
for select using(status='published' or public.is_admin());

drop policy if exists "admins manage land rules" on public.land_analysis_rules;
create policy "admins manage land rules" on public.land_analysis_rules
for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "users own land analyses read" on public.land_analyses;
create policy "users own land analyses read" on public.land_analyses
for select using(auth.uid()=user_id or public.is_admin());

drop policy if exists "users create own land analyses" on public.land_analyses;
create policy "users create own land analyses" on public.land_analyses
for insert with check(auth.uid()=user_id);

drop policy if exists "users delete own land analyses" on public.land_analyses;
create policy "users delete own land analyses" on public.land_analyses
for delete using(auth.uid()=user_id or public.is_admin());

delete from public.land_analysis_rules;

insert into public.land_analysis_rules(rule_type,category,severity,title,message,next_step,conditions,position,source_url) values
('checklist','identificacao','info','Confirmar identificação do prédio','Cruzar artigo matricial, descrição predial, localização/cartografia e área antes de interpretar o planeamento.',null,'{}',10,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('checklist','planeamento','info','Consultar PDM e instrumentos em vigor','Localizar o prédio no instrumento territorial aplicável e ler planta e regulamento em conjunto.',null,'{}',20,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('checklist','condicionantes','info','Consultar planta de condicionantes','Verificar REN, RAN, domínio hídrico, património, vias, infraestruturas e outras servidões/restrições aplicáveis.',null,'{}',30,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2015-105297982'),
('checklist','acesso','info','Confirmar acesso jurídico e físico','Validar frente para via, servidões, capacidade de acesso e eventuais obras necessárias.',null,'{}',40,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('checklist','infraestruturas','info','Confirmar disponibilidade de redes','Água, saneamento, eletricidade e telecomunicações devem ser confirmados junto das entidades competentes.',null,'{}',50,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('checklist','urbanismo','info','Identificar o procedimento urbanístico provável','Distinguir licença, comunicação prévia, PIP, loteamento e outros mecanismos aplicáveis à operação concreta.',null,'{}',60,'https://diariodarepublica.pt/dr/detalhe/decreto-lei/108-2026-1128002421'),
('checklist','comercial','info','Separar potencial de capacidade confirmada','No dossier e anúncio, identificar claramente o nível de certeza da informação urbanística.',null,'{}',70,'https://diariodarepublica.pt/dr/detalhe/lei/15-2013-257806'),

('alert','planeamento','alto','PDM ainda não consultado','Sem consulta do planeamento aplicável não existe base suficiente para afirmar capacidade construtiva.','Consultar o PDM/IGT em vigor e o respetivo regulamento antes de avançar.', '{"pdm":"nao"}',100,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('alert','solo','alto','Classificação do solo desconhecida','A designação comercial “urbanizável” não substitui a classificação e qualificação do solo em vigor.','Identificar a classificação/qualificação no plano aplicável.', '{"soil":"desconhecido"}',110,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2015-105297982'),
('alert','condicionantes','alto','Condicionantes não verificadas','Podem existir restrições que alterem ou inviabilizem a solução pretendida.','Consultar planta de condicionantes e regimes especiais relevantes.', '{"constraints":"desconhecidas"}',120,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('alert','condicionantes','medio','Existem condicionantes identificadas','A existência de condicionante não significa automaticamente proibição, mas exige análise do respetivo regime.','Identificar a área afetada, o regime aplicável e a entidade competente.', '{"constraints":"identificadas"}',130,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2015-105297982'),
('alert','acesso','alto','Sem acesso identificado','A inexistência de acesso adequado pode comprometer significativamente a operação.','Obter análise jurídica/técnica do acesso e das soluções possíveis.', '{"access":"sem_acesso"}',140,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('alert','acesso','medio','Acesso por servidão','A existência, conteúdo e suficiência da servidão devem ser confirmados documentalmente.','Consultar registo/títulos e validar tecnicamente o acesso necessário à operação.', '{"access":"servidao"}',150,'https://conservatoria.justica.gov.pt/predio/certidoes-e-informacoes-de-registo-predial'),
('alert','infraestruturas','medio','Infraestruturas incompletas','Extensões ou obras de urbanização podem alterar custo e prazo do projeto.','Pedir informação às entidades gestoras e estimar encargos de ligação/urbanização.', '{"infra":["parciais","ausentes","desconhecidas"]}',160,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('alert','pip','medio','Sem PIP para uma operação de desenvolvimento','Quando a decisão económica depende de uma capacidade urbanística concreta, um PIP pode reduzir incerteza.','Avaliar com arquiteto/urbanista se um PIP é adequado ao objetivo.', '{"objective":["varias_moradias","empreendimento","loteamento"],"pip":"nao"}',170,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),

('next_step','sequencia','info','1. Fechar a identificação territorial','Confirmar exatamente qual é o prédio.','Reunir certidão, caderneta, localização georreferenciada e elementos cartográficos.','{}',200,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('next_step','sequencia','info','2. Fazer leitura conjunta de planeamento','Não ler apenas uma planta isolada.','Cruzar ordenamento, regulamento e condicionantes e registar os artigos relevantes.','{}',210,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('next_step','sequencia','info','3. Validar acesso e redes','Transformar proximidade visual em informação confirmada.','Confirmar acesso, água, saneamento, eletricidade e eventuais obras de urbanização.','{}',220,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('next_step','sequencia','info','4. Definir a operação pretendida','A pergunta urbanística deve ser concreta.','Trabalhar com técnico habilitado para testar implantação, parâmetros e procedimento adequado.','{}',230,'https://diariodarepublica.pt/dr/detalhe/portaria/320-2026-1153698591'),
('next_step','sequencia','info','5. Reduzir incerteza antes de comercializar','O nível de certeza deve ser proporcional ao suporte existente.','Quando adequado, obter PIP/informação municipal e refletir o grau de confirmação no anúncio e negociação.','{}',240,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875');

commit;

select rule_type,count(*) from public.land_analysis_rules group by rule_type order by rule_type;
