-- V6.2 — Ferramenta “Posso mudar o uso deste imóvel?”
-- Incremental. Não elimina conteúdos anteriores.
-- Verificação jurídica de referência: 18/08/2026
begin;

create table if not exists public.use_change_rules (
  id bigint generated by default as identity primary key,
  rule_type text not null check (rule_type in ('checklist','alert','next_step')),
  severity text not null default 'info' check (severity in ('info','baixo','medio','alto')),
  title text not null,
  message text not null,
  next_step text,
  conditions jsonb not null default '{}'::jsonb,
  position int not null default 100,
  verified_at date not null default date '2026-08-18',
  source_url text,
  status text not null default 'published'
);

create table if not exists public.use_change_analyses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  municipality text,
  property_type text,
  current_use text not null,
  intended_use text not null,
  autonomous_fraction boolean,
  works text not null,
  title_known text not null,
  answers jsonb not null default '{}'::jsonb,
  result_status text not null,
  checklist jsonb not null default '[]'::jsonb,
  alerts jsonb not null default '[]'::jsonb,
  next_steps jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.use_change_rules enable row level security;
alter table public.use_change_analyses enable row level security;

drop policy if exists "published use change rules readable" on public.use_change_rules;
create policy "published use change rules readable"
on public.use_change_rules for select
using (status='published' or public.is_admin());

drop policy if exists "admins manage use change rules" on public.use_change_rules;
create policy "admins manage use change rules"
on public.use_change_rules for all
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users own use change analyses read" on public.use_change_analyses;
create policy "users own use change analyses read"
on public.use_change_analyses for select
using (auth.uid()=user_id or public.is_admin());

drop policy if exists "users create own use change analyses" on public.use_change_analyses;
create policy "users create own use change analyses"
on public.use_change_analyses for insert
with check (auth.uid()=user_id);

drop policy if exists "users delete own use change analyses" on public.use_change_analyses;
create policy "users delete own use change analyses"
on public.use_change_analyses for delete
using (auth.uid()=user_id or public.is_admin());

delete from public.use_change_rules;

insert into public.use_change_rules(rule_type,severity,title,message,next_step,conditions,position,source_url) values
('checklist','info','Confirmar o uso atualmente titulado','Não use apenas a designação da caderneta ou do anúncio. Consulte o título/informação urbanística municipal e confronte-o com a realidade.',null,'{}',10,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('checklist','info','Confirmar compatibilidade do novo uso','Verifique PDM, planos aplicáveis e regulamentos municipais para saber se o uso pretendido é admissível.',null,'{}',20,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('checklist','info','Reunir elementos do imóvel','Certidão predial, caderneta, plantas/projetos disponíveis, título de utilização/informação municipal e propriedade horizontal quando aplicável.',null,'{}',30,'https://justica.gov.pt/Servicos/Balcao-Casa-Pronta'),
('checklist','info','Verificar requisitos técnicos','A aptidão para o novo uso deve ser validada por técnico competente: configuração, segurança, acessibilidade, ventilação, instalações e restantes requisitos aplicáveis.',null,'{}',40,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),

('alert','alto','Uso atual não confirmado','Sem saber qual é o uso atualmente titulado, não é seguro concluir qual a alteração necessária.','Obter o título/informação municipal antes de anunciar a conversão como viável.','{"title_known":"nao"}',100,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('alert','medio','A conversão exige obras','Primeiro é necessário enquadrar urbanisticamente as obras destinadas ao novo uso.','Pedir a um arquiteto/técnico habilitado que determine o procedimento das obras e os requisitos do uso pretendido.','{"works":"sim"}',110,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('alert','medio','Não sabe ainda se são necessárias obras','A aptidão física para o novo uso ainda não está confirmada.','Fazer avaliação técnica antes de escolher o procedimento.','{"works":"desconhecido"}',120,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('alert','medio','Fração autónoma: verificar propriedade horizontal','Urbanismo e propriedade horizontal são planos diferentes. Consulte o título constitutivo e as regras aplicáveis.','Confirmar o fim da fração no título constitutivo e eventuais limitações relevantes.','{"autonomous_fraction":true}',130,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1966-34509075'),
('alert','baixo','Conversão para habitação — regra especial do condomínio','O artigo 1422.º-B do Código Civil prevê que a alteração do fim ou uso de uma fração para habitação não carece de autorização dos restantes condóminos, sem dispensar o procedimento urbanístico e a atualização documental aplicáveis.','Após a alteração junto da Câmara, verificar a atualização do título constitutivo e a comunicação ao administrador nos termos legais.','{"autonomous_fraction":true,"intended_use":"habitacao"}',140,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1966-34509075'),
('alert','medio','Serviços não define sozinho a atividade','Um uso urbanístico de serviços não garante que qualquer atividade específica possa funcionar no espaço.','Identificar a atividade concreta e verificar requisitos/licenciamentos setoriais adicionais.','{"intended_use":"servicos"}',150,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),

('next_step','info','1. Fechar a situação documental','Confirmar uso atual e configuração documental do imóvel.','Reunir título/informação municipal, certidão, matriz, plantas e propriedade horizontal quando exista.','{}',200,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('next_step','info','2. Validar o novo uso no planeamento','O novo uso tem de ser admissível naquele local e edifício.','Cruzar PDM/planos e regulamento municipal com a utilização pretendida.','{}',210,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('next_step','info','3. Determinar se há obras','A existência de obras muda o percurso procedimental.','Obter avaliação técnica e, se houver obras, enquadrar primeiro o respetivo procedimento.','{}',220,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('next_step','info','4. Determinar o procedimento de utilização','Sem obra prévia sujeita ao controlo do artigo 62.º-A, analisar o artigo 62.º-B; após obras abrangidas, analisar o artigo 62.º-A.','Confirmar a redação vigente e a situação concreta antes da submissão.','{}',230,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('next_step','info','5. Atualizar e comercializar com rigor','A documentação e o anúncio devem refletir o estado real da conversão.','Só apresentar o novo uso como concluído depois de completado o percurso aplicável.','{}',240,'https://diariodarepublica.pt/dr/detalhe/lei/15-2013-257806');

commit;

select rule_type,count(*) from public.use_change_rules group by rule_type order by rule_type;
