begin;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Documentos Base — aprender a cruzar informação','Documentação Imobiliária — módulo 1',1,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=1);
update public.modules m set title='Documentos Base — aprender a cruzar informação',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=1;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Certidão predial: o que realmente diz','d1-1-certidao-predial-o-que-realmente-diz','{"intro": "Aprenda a tratar certidão predial: o que realmente diz como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar certidão predial: o que realmente diz como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=1
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Caderneta predial: função fiscal e validade','d1-2-caderneta-predial-funcao-fiscal-e-validade','{"intro": "Aprenda a tratar caderneta predial: função fiscal e validade como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar caderneta predial: função fiscal e validade como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=1
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Cruzamento documental profissional','d1-3-cruzamento-documental-profissional','{"intro": "Aprenda a tratar cruzamento documental profissional como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar cruzamento documental profissional como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=1
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=1;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 1 — Documentos Base — aprender a cruzar informação' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 1 — Documentos Base — aprender a cruzar informação',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Apartamento / Fração Autónoma','Documentação Imobiliária — módulo 2',2,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=2);
update public.modules m set title='Apartamento / Fração Autónoma',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=2;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Checklist de apartamento','d2-1-checklist-de-apartamento','{"intro": "Aprenda a tratar checklist de apartamento como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar checklist de apartamento como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=2
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Condomínio e encargos','d2-2-condominio-e-encargos','{"intro": "Aprenda a tratar condomínio e encargos como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar condomínio e encargos como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=2
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Divergências na fração','d2-3-divergencias-na-fracao','{"intro": "Aprenda a tratar divergências na fração como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar divergências na fração como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=2
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=2;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 2 — Apartamento / Fração Autónoma' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 2 — Apartamento / Fração Autónoma',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Moradia','Documentação Imobiliária — módulo 3',3,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=3);
update public.modules m set title='Moradia',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=3;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Checklist de moradia','d3-1-checklist-de-moradia','{"intro": "Aprenda a tratar checklist de moradia como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar checklist de moradia como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=3
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Moradia antiga','d3-2-moradia-antiga','{"intro": "Aprenda a tratar moradia antiga como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar moradia antiga como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=3
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Logradouro, anexos e limites','d3-3-logradouro-anexos-e-limites','{"intro": "Aprenda a tratar logradouro, anexos e limites como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar logradouro, anexos e limites como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=3
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=3;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 3 — Moradia' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 3 — Moradia',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Terreno','Documentação Imobiliária — módulo 4',4,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=4);
update public.modules m set title='Terreno',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=4;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Checklist documental de terreno','d4-1-checklist-documental-de-terreno','{"intro": "Aprenda a tratar checklist documental de terreno como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar checklist documental de terreno como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=4
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Terreno com projeto ou PIP','d4-2-terreno-com-projeto-ou-pip','{"intro": "Aprenda a tratar terreno com projeto ou pip como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar terreno com projeto ou pip como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=4
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Como anunciar potencial construtivo','d4-3-como-anunciar-potencial-construtivo','{"intro": "Aprenda a tratar como anunciar potencial construtivo como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar como anunciar potencial construtivo como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=4
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=4;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 4 — Terreno' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 4 — Terreno',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Loja, Escritório e Serviços','Documentação Imobiliária — módulo 5',5,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=5);
update public.modules m set title='Loja, Escritório e Serviços',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=5;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Checklist comercial','d5-1-checklist-comercial','{"intro": "Aprenda a tratar checklist comercial como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar checklist comercial como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=5
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Loja não é automaticamente qualquer comércio','d5-2-loja-nao-e-automaticamente-qualquer-comercio','{"intro": "Aprenda a tratar loja não é automaticamente qualquer comércio como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar loja não é automaticamente qualquer comércio como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=5
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Conversão de uso','d5-3-conversao-de-uso','{"intro": "Aprenda a tratar conversão de uso como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar conversão de uso como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=5
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=5;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 5 — Loja, Escritório e Serviços' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 5 — Loja, Escritório e Serviços',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Armazém e Imóveis Industriais','Documentação Imobiliária — módulo 6',6,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=6);
update public.modules m set title='Armazém e Imóveis Industriais',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=6;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Checklist de armazém','d6-1-checklist-de-armazem','{"intro": "Aprenda a tratar checklist de armazém como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar checklist de armazém como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=6
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Armazém para serviços/comércio','d6-2-armazem-para-servicos-comercio','{"intro": "Aprenda a tratar armazém para serviços/comércio como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar armazém para serviços/comércio como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=6
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Infraestruturas e operação','d6-3-infraestruturas-e-operacao','{"intro": "Aprenda a tratar infraestruturas e operação como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar infraestruturas e operação como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=6
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=6;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 6 — Armazém e Imóveis Industriais' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 6 — Armazém e Imóveis Industriais',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Prédio Inteiro','Documentação Imobiliária — módulo 7',7,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=7);
update public.modules m set title='Prédio Inteiro',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=7;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Checklist de prédio','d7-1-checklist-de-predio','{"intro": "Aprenda a tratar checklist de prédio como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar checklist de prédio como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=7
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Prédio em propriedade total','d7-2-predio-em-propriedade-total','{"intro": "Aprenda a tratar prédio em propriedade total como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar prédio em propriedade total como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=7
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Investimento e rendimentos','d7-3-investimento-e-rendimentos','{"intro": "Aprenda a tratar investimento e rendimentos como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar investimento e rendimentos como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=7
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=7;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 7 — Prédio Inteiro' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 7 — Prédio Inteiro',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Imóvel em Construção / Projeto','Documentação Imobiliária — módulo 8',8,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=8);
update public.modules m set title='Imóvel em Construção / Projeto',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=8;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'O que está realmente aprovado','d8-1-o-que-esta-realmente-aprovado','{"intro": "Aprenda a tratar o que está realmente aprovado como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar o que está realmente aprovado como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=8
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Ficha técnica e informação ao consumidor','d8-2-ficha-tecnica-e-informacao-ao-consumidor','{"intro": "Aprenda a tratar ficha técnica e informação ao consumidor como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar ficha técnica e informação ao consumidor como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=8
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Pré-certificado energético','d8-3-pre-certificado-energetico','{"intro": "Aprenda a tratar pré-certificado energético como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar pré-certificado energético como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=8
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=8;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 8 — Imóvel em Construção / Projeto' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 8 — Imóvel em Construção / Projeto',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Imóvel Arrendado','Documentação Imobiliária — módulo 9',9,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=9);
update public.modules m set title='Imóvel Arrendado',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=9;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Comprar imóvel arrendado','d9-1-comprar-imovel-arrendado','{"intro": "Aprenda a tratar comprar imóvel arrendado como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar comprar imóvel arrendado como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=9
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Vender com arrendatário','d9-2-vender-com-arrendatario','{"intro": "Aprenda a tratar vender com arrendatário como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar vender com arrendatário como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=9
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Arrendar imóvel','d9-3-arrendar-imovel','{"intro": "Aprenda a tratar arrendar imóvel como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar arrendar imóvel como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=9
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=9;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 9 — Imóvel Arrendado' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 9 — Imóvel Arrendado',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Certificado Energético','Documentação Imobiliária — módulo 10',10,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=10);
update public.modules m set title='Certificado Energético',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=10;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Quando é obrigatório','d10-1-quando-e-obrigatorio','{"intro": "Aprenda a tratar quando é obrigatório como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar quando é obrigatório como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=10
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Publicidade','d10-2-publicidade','{"intro": "Aprenda a tratar publicidade como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar publicidade como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=10
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Exceções e validade','d10-3-excecoes-e-validade','{"intro": "Aprenda a tratar exceções e validade como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar exceções e validade como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=10
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=10;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 10 — Certificado Energético' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 10 — Certificado Energético',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Venda — preparação do negócio','Documentação Imobiliária — módulo 11',11,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=11);
update public.modules m set title='Venda — preparação do negócio',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=11;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Dossier antes do CPCV','d11-1-dossier-antes-do-cpcv','{"intro": "Aprenda a tratar dossier antes do cpcv como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar dossier antes do cpcv como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=11
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Preferências públicas','d11-2-preferencias-publicas','{"intro": "Aprenda a tratar preferências públicas como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar preferências públicas como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=11
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Simplex e a escritura','d11-3-simplex-e-a-escritura','{"intro": "Aprenda a tratar simplex e a escritura como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar simplex e a escritura como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=11
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=11;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 11 — Venda — preparação do negócio' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 11 — Venda — preparação do negócio',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
insert into public.modules(course_id,title,description,position,status)
select c.id,'Casos Práticos e Avaliação','Documentação Imobiliária — módulo 12',12,'published' from public.courses c
where c.slug='documentacao-imobiliaria' and not exists(select 1 from public.modules m where m.course_id=c.id and m.position=12);
update public.modules m set title='Casos Práticos e Avaliação',status='published' from public.courses c where m.course_id=c.id and c.slug='documentacao-imobiliaria' and m.position=12;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Apartamento com marquise','d12-1-apartamento-com-marquise','{"intro": "Aprenda a tratar apartamento com marquise como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar apartamento com marquise como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',1
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=12
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Moradia com anexo','d12-2-moradia-com-anexo','{"intro": "Aprenda a tratar moradia com anexo como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar moradia com anexo como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',2
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=12
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
insert into public.lessons(module_id,title,slug,content,duration_minutes,legal_sensitive,verified_at,source_url,status,position)
select m.id,'Terreno ''para 6 moradias''','d12-3-terreno-para-6-moradias','{"intro": "Aprenda a tratar terreno ''para 6 moradias'' como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional.", "sections": [{"title": "O que verificar", "body": "Aprenda a tratar terreno ''para 6 moradias'' como parte de uma due diligence documental: o objetivo é perceber o que o documento prova, o que não prova, como o cruzar com outras fontes e que divergências exigem validação adicional."}, {"title": "Como cruzar", "body": "Compare registo, matriz, urbanismo, propriedade horizontal, energia e realidade física conforme o tipo de imóvel e a operação."}, {"title": "Na comercialização", "body": "Comunique apenas factos suportados e identifique informação pendente de confirmação."}], "takeaway": "Documento obtido não significa due diligence concluída: confirme conteúdo, atualidade, correspondência e efeito no negócio."}'::jsonb,10,true,date '2026-08-18','https://justica.gov.pt/Servicos/Balcao-Casa-Pronta','published',3
from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=12
on conflict(module_id,slug) do update set title=excluded.title,content=excluded.content,verified_at=excluded.verified_at,status='published',position=excluded.position;
DO $$ declare m_id bigint;q_id bigint;qu_id bigint; begin
select m.id into m_id from public.modules m join public.courses c on c.id=m.course_id where c.slug='documentacao-imobiliaria' and m.position=12;
select id into q_id from public.quizzes where module_id=m_id and title='Teste · Documentação 12 — Casos Práticos e Avaliação' limit 1;
if q_id is null then insert into public.quizzes(module_id,title,pass_percentage) values(m_id,'Teste · Documentação 12 — Casos Práticos e Avaliação',80) returning id into q_id; end if;
if not exists(select 1 from public.questions where quiz_id=q_id) then
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Um único documento prova sozinho toda a situação jurídica, fiscal e urbanística do imóvel?','É necessário cruzar fontes.',1) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A caderneta predial tem natureza essencialmente fiscal?','A matriz não substitui registo ou urbanismo.',2) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'Divergências relevantes devem ser comunicadas ao interessado?','A mediação exige exatidão e clareza.',3) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A eliminação da exibição da autorização de utilização na transmissão significa que a situação urbanística deixou de interessar?','Simplificação formal não equivale a legalização.',4) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',false,1),(qu_id,'Não',true,2);
insert into public.questions(quiz_id,question,explanation,position) values(q_id,'A checklist deve variar com o tipo de imóvel e a operação?','As verificações variam.',5) returning id into qu_id;
insert into public.answers(question_id,answer,is_correct,position) values(qu_id,'Sim',true,1),(qu_id,'Não',false,2);
end if; end $$;
commit;
select c.title,count(distinct m.id) modulos,count(distinct l.id) aulas,count(distinct q.id) testes
from public.courses c left join public.modules m on m.course_id=c.id left join public.lessons l on l.module_id=m.id
left join public.quizzes q on q.module_id=m.id where c.slug='documentacao-imobiliaria' group by c.title;