-- V7 — Documentação Imobiliária + ferramenta "Que documentos preciso?"
-- Verificação de referência: 18/08/2026
begin;
insert into public.courses(title,slug,description,level,status,position)
values('Documentação Imobiliária','documentacao-imobiliaria',
'Documentos, verificações e alertas por tipo de imóvel e operação: angariação, venda, compra e arrendamento.',
'Especialização','published',12)
on conflict(slug) do update set title=excluded.title,description=excluded.description,status='published',position=12;

create table if not exists public.document_check_rules(
 id bigint generated by default as identity primary key,
 property_type text not null, operation text not null, document_name text not null,
 category text not null, requirement text not null default 'verificar',
 why_needed text not null, where_to_get text, validity text, alert_text text,
 conditions jsonb not null default '{}'::jsonb, position int not null default 100,
 verified_at date not null default date '2026-08-18', source_url text,
 status text not null default 'published'
);
create table if not exists public.document_check_analyses(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 property_type text not null, operation text not null, municipality text,
 answers jsonb not null default '{}'::jsonb, checklist jsonb not null default '[]'::jsonb,
 alerts jsonb not null default '[]'::jsonb, created_at timestamptz not null default now()
);
alter table public.document_check_rules enable row level security;
alter table public.document_check_analyses enable row level security;
drop policy if exists "published document rules readable" on public.document_check_rules;
create policy "published document rules readable" on public.document_check_rules for select using(status='published' or public.is_admin());
drop policy if exists "admins manage document rules" on public.document_check_rules;
create policy "admins manage document rules" on public.document_check_rules for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "users own document analyses read" on public.document_check_analyses;
create policy "users own document analyses read" on public.document_check_analyses for select using(auth.uid()=user_id or public.is_admin());
drop policy if exists "users create document analyses" on public.document_check_analyses;
create policy "users create document analyses" on public.document_check_analyses for insert with check(auth.uid()=user_id);
delete from public.document_check_rules;

insert into public.document_check_rules(property_type,operation,document_name,category,requirement,why_needed,where_to_get,validity,alert_text,position,source_url) values
('all','all','Certidão permanente do registo predial','Registo','essencial','Verificar descrição, titularidade, inscrições, ónus e encargos registados.','Predial Online / Conservatória','Confirmar informação atual.','Cruzar titulares, descrição, áreas e ónus com os restantes documentos.',10,'https://justica.gov.pt/Servicos/Pedir-certidao-permanente-predial'),
('all','all','Caderneta predial','Fiscal','essencial','Identifica dados matriciais, localização, características, titulares fiscais e VPT.','Portal das Finanças','12 meses.','A matriz é fiscal: divergências com registo, realidade ou urbanismo exigem investigação.',20,'https://info.portaldasfinancas.gov.pt/pt/apoio_ao_contribuinte/Cidadaos/Casa_e_propriedades/Certidoes_e_comprovativos/Paginas/default.aspx'),
('all','angariacao','Contrato de mediação imobiliária','Mediação','obrigatorio','O CMI é escrito e identifica imóvel, negócio, remuneração, seguro e outros elementos legais.','Empresa de mediação','Durante a relação contratual.','O objeto mediado e os ónus/encargos devem estar corretamente identificados.',30,'https://diariodarepublica.pt/dr/legislacao-consolidada/lei/2013-74934612-169211975'),
('all','venda','Identificação e legitimidade dos vendedores','Titularidade','essencial','A mediadora deve certificar capacidade e legitimidade para contratar.','Documentos das partes + registo','Atual.','Verificar compropriedade, herança, representação e procurações.',40,'https://diariodarepublica.pt/dr/detalhe/lei/15-2013-257806'),
('all','compra','Identificação e legitimidade das partes','Titularidade','essencial','A transação exige identificação dos intervenientes e verificação da posição jurídica do vendedor.','Documentos das partes + registo','Atual.','Não confundir titular fiscal com titular registado.',45,'https://justica.gov.pt/Servicos/Balcao-Casa-Pronta');

insert into public.document_check_rules(property_type,operation,document_name,category,requirement,why_needed,where_to_get,validity,alert_text,position,source_url)
select p,o,'Certificado energético ou prova de exceção','Energia','obrigatorio',
'Nos edifícios abrangidos pelo SCE, a classe energética deve constar dos anúncios e o certificado válido deve ser disponibilizado nos momentos legalmente previstos.',
'Perito Qualificado / Portal SCE','Confirmar validade no Portal SCE.','Não publique um edifício abrangido sem classe energética válida; confirme exceções legais.',60,'https://www.sce.pt/perguntas-frequentes/'
from (values('apartamento'),('moradia'),('loja'),('escritorio'),('armazem'),('predio'),('construcao')) x(p)
cross join (values('angariacao'),('venda'),('compra'),('arrendamento')) y(o);

insert into public.document_check_rules(property_type,operation,document_name,category,requirement,why_needed,where_to_get,validity,alert_text,position,source_url)
select p,o,'Título/informação urbanística de utilização e histórico municipal','Urbanismo','verificar',
'Confirma o uso titulado, obras e situação urbanística. Desde 2024 deixou de ser obrigatória a exibição/prova da autorização de utilização e da FTH no ato de transmissão, sem eliminar a due diligence urbanística.',
'Câmara Municipal / arquivo do proprietário','Conforme documento e situação atual.','Não confundir “não é obrigatório exibir na escritura” com “não é necessário verificar a situação urbanística”.',70,'https://diariodarepublica.pt/dr/detalhe/decreto-lei/10-2024-836222484'
from (values('apartamento'),('moradia'),('loja'),('escritorio'),('armazem'),('predio')) x(p)
cross join (values('angariacao'),('venda'),('compra')) y(o);

insert into public.document_check_rules(property_type,operation,document_name,category,requirement,why_needed,where_to_get,validity,alert_text,position,source_url)
select p,o,'Título constitutivo da propriedade horizontal','Condomínio','essencial','Confirma frações, permilagens, fim atribuído e partes comuns.','Conservatória / condomínio','Confirmar versão atual e alterações.','Comparar uso efetivo com o título e a documentação urbanística.',80,'https://justica.gov.pt/Servicos/Balcao-Casa-Pronta'
from (values('apartamento'),('loja'),('escritorio')) x(p)
cross join (values('angariacao'),('venda'),('compra')) y(o);

insert into public.document_check_rules(property_type,operation,document_name,category,requirement,why_needed,where_to_get,validity,alert_text,position,source_url)
select p,'venda','Declaração do condomínio relativa a encargos/dívidas','Condomínio','verificar','Verificar a situação dos encargos de condomínio e o regime aplicável à transmissão.','Administrador do condomínio','Deve refletir a situação relevante para a transmissão.','Confirmar valores, natureza e vencimento dos encargos.',90,'https://diariodarepublica.pt/dr/detalhe/lei/8-2022-177350570'
from (values('apartamento'),('loja'),('escritorio')) x(p);

insert into public.document_check_rules(property_type,operation,document_name,category,requirement,why_needed,where_to_get,validity,alert_text,position,source_url)
select p,'venda','Verificação / anúncio de direito legal de preferência pública','Preferências','condicional','Pode ser necessário em imóveis classificados, em vias de classificação, áreas protegidas, ARU ou outras situações legais.','Casa Pronta + entidades/município','No serviço online, as entidades têm 10 dias úteis para responder.','Verificar antes de marcar o negócio; o anúncio comunica preço e condições essenciais.',100,'https://justica.gov.pt/en-gb/Servicos/Colocar-anuncio-para-o-exercicio-do-direito-legal-de-preferencia'
from (values('apartamento'),('moradia'),('loja'),('escritorio'),('armazem'),('predio'),('terreno')) x(p);

insert into public.document_check_rules(property_type,operation,document_name,category,requirement,why_needed,where_to_get,validity,alert_text,position,source_url) values
('terreno','all','Instrumentos de gestão territorial aplicáveis','Urbanismo','essencial','Identificar classificação/qualificação, usos e parâmetros.','SNIT/DGT e Município','Confirmar instrumentos em vigor.','Não usar “urbanizável” como garantia sem suporte.',110,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('terreno','all','Planta de condicionantes e regimes especiais','Condicionantes','essencial','Identificar REN, RAN, domínio hídrico, património, infraestruturas e outras restrições.','SNIT/DGT, Município e entidades','Atual.','Analisar cada condicionante no respetivo regime.',120,'https://www.dgterritorio.gov.pt/atividades/ordenamento/snit'),
('terreno','all','PIP / informação municipal, quando exista','Urbanismo','condicional','Reduz incerteza sobre uma operação concreta.','Câmara Municipal','Confirmar validade e efeitos.','Não transformar leitura preliminar em “projeto aprovado”.',130,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('construcao','all','Título/procedimento urbanístico da obra e projeto','Construção','essencial','Permite saber o que está autorizado/comunicado e comparar com o comercializado.','Município / promotor','Confirmar estado atual.','A publicidade deve corresponder ao projeto e estado real.',140,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'),
('construcao','all','Ficha técnica da habitação / versão provisória, quando aplicável','Informação técnica','verificar','A eliminação da exibição no ato de transmissão não eliminou automaticamente todos os deveres do regime da FTH.','Promotor / proprietário / Câmara','Conforme regime aplicável.','Distinguir existência/informação da antiga formalidade de exibição.',150,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/2004-156126559');

insert into public.document_check_rules(property_type,operation,document_name,category,requirement,why_needed,where_to_get,validity,alert_text,position,source_url)
select p,'arrendamento','Confirmação do uso e aptidão para o arrendamento pretendido','Utilização','essencial','O uso contratual deve ser compatível com urbanismo, propriedade horizontal e requisitos da atividade quando aplicáveis.','Município + documentação do imóvel','Atual.','Serviços/comércio podem exigir requisitos setoriais adicionais.',160,'https://diariodarepublica.pt/dr/legislacao-consolidada/decreto-lei/1999-34567875'
from (values('apartamento'),('moradia'),('loja'),('escritorio'),('armazem')) x(p);
commit;
