'use server'
import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

async function adminClient(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
 const {data:p}=await supabase.from('profiles').select('role').eq('id',user.id).single();if(p?.role!=='admin')redirect('/dashboard');return supabase
}
export async function createCourse(formData:FormData){const s=await adminClient();const title=String(formData.get('title')||'').trim(),slug=String(formData.get('slug')||'').trim(),description=String(formData.get('description')||'').trim(),level=String(formData.get('level')||'').trim();if(!title||!slug)return;await s.from('courses').insert({title,slug,description,level,status:'draft',position:99});revalidatePath('/admin');revalidatePath('/academia')}
export async function createModule(formData:FormData){const s=await adminClient();const course_id=Number(formData.get('course_id')),title=String(formData.get('title')||'').trim(),description=String(formData.get('description')||'').trim(),position=Number(formData.get('position')||1);if(!course_id||!title)return;await s.from('modules').insert({course_id,title,description,position,status:'draft'});revalidatePath('/admin')}
export async function createLesson(formData:FormData){const s=await adminClient();const module_id=Number(formData.get('module_id')),title=String(formData.get('title')||'').trim(),slug=String(formData.get('slug')||'').trim(),intro=String(formData.get('intro')||'').trim(),duration_minutes=Number(formData.get('duration_minutes')||8),legal_sensitive=formData.get('legal_sensitive')==='on',source_url=String(formData.get('source_url')||'').trim()||null;if(!module_id||!title||!slug)return;await s.from('lessons').insert({module_id,title,slug,duration_minutes,legal_sensitive,verified_at:legal_sensitive?new Date().toISOString().slice(0,10):null,source_url,status:'draft',position:99,content:{intro,sections:[],takeaway:''}});revalidatePath('/admin')}
export async function createRadarUpdate(formData:FormData){const s=await adminClient();const title=String(formData.get('title')||'').trim(),topic=String(formData.get('topic')||'').trim(),summary=String(formData.get('summary')||'').trim(),impact=String(formData.get('impact')||'').trim(),source_url=String(formData.get('source_url')||'').trim();if(!title||!topic||!summary||!source_url)return;await s.from('legislative_updates').insert({title,topic,summary,impact,source_url,status:'draft',verified_at:new Date().toISOString().slice(0,10)});revalidatePath('/admin');revalidatePath('/radar')}
export async function togglePublish(formData:FormData){const s=await adminClient();const table=String(formData.get('table')||''),id=Number(formData.get('id')),status=String(formData.get('status'))==='published'?'draft':'published';if(!['courses','modules','lessons','legislative_updates'].includes(table)||!id)return;await s.from(table as any).update({status}).eq('id',id);revalidatePath('/admin');revalidatePath('/academia');revalidatePath('/radar')}
