import AppShell from '@/components/AppShell'
import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { createCourse,createModule,createLesson,createRadarUpdate,togglePublish } from './actions'

export default async function Admin(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('role').eq('id',user.id).single();if(profile?.role!=='admin')redirect('/dashboard');
 const [{data:courses},{data:modules},{data:lessons},{data:updates},{count:usersCount}]=await Promise.all([
  supabase.from('courses').select('id,title,slug,status,position').order('position'),
  supabase.from('modules').select('id,title,course_id,status,position').order('position'),
  supabase.from('lessons').select('id,title,module_id,status,legal_sensitive,verified_at').order('id',{ascending:false}).limit(30),
  supabase.from('legislative_updates').select('id,title,topic,status,verified_at').order('created_at',{ascending:false}).limit(20),
  supabase.from('profiles').select('*',{count:'exact',head:true})
 ])
 return <AppShell><div className="topbar"><div><div className="eyebrow">Acesso reservado</div><h1>Administração</h1><p className="muted">Gerir formação, publicação e atualizações sem alterar o código.</p></div><span className="badge">Administrador</span></div>
 <section className="section grid grid-3"><div className="card"><div className="muted">Utilizadores</div><div className="metric">{usersCount??0}</div></div><div className="card"><div className="muted">Cursos</div><div className="metric">{courses?.length??0}</div></div><div className="card"><div className="muted">Aulas registadas</div><div className="metric">{lessons?.length??0}</div></div></section>
 <section className="section admin-grid"><div className="card"><h2>Novo curso</h2><form action={createCourse}><label className="field">Título<input name="title" required/></label><label className="field">Slug<input name="slug" placeholder="ex: arrendamento" required/></label><label className="field">Nível<input name="level" placeholder="Especialização"/></label><label className="field">Descrição<textarea name="description" rows={3}/></label><button className="btn" type="submit">Criar rascunho</button></form></div>
 <div className="card"><h2>Novo módulo</h2><form action={createModule}><label className="field">Curso<select name="course_id" required>{(courses||[]).map((c:any)=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label className="field">Título<input name="title" required/></label><label className="field">Descrição<textarea name="description" rows={3}/></label><label className="field">Posição<input type="number" name="position" defaultValue="1" min="1"/></label><button className="btn" type="submit">Criar módulo</button></form></div></section>
 <section className="section admin-grid"><div className="card"><h2>Nova aula</h2><form action={createLesson}><label className="field">Módulo<select name="module_id" required>{(modules||[]).map((m:any)=><option value={m.id} key={m.id}>{m.title}</option>)}</select></label><label className="field">Título<input name="title" required/></label><label className="field">Slug<input name="slug" required/></label><label className="field">Introdução<textarea name="intro" rows={4}/></label><label className="field">Duração (min)<input type="number" name="duration_minutes" defaultValue="8"/></label><label className="check-line"><input type="checkbox" name="legal_sensitive"/> Conteúdo legal/documental</label><label className="field">Fonte oficial<input name="source_url" type="url"/></label><button className="btn" type="submit">Criar aula</button></form></div>
 <div className="card"><h2>Nova atualização legislativa</h2><form action={createRadarUpdate}><label className="field">Título<input name="title" required/></label><label className="field">Tema<input name="topic" required/></label><label className="field">Resumo<textarea name="summary" rows={4} required/></label><label className="field">Impacto<textarea name="impact" rows={3}/></label><label className="field">Fonte oficial<input type="url" name="source_url" required/></label><button className="btn" type="submit">Guardar no Radar</button></form></div></section>
 <section className="section card"><h2>Publicação de cursos</h2><table className="table"><thead><tr><th>Curso</th><th>Estado</th><th></th></tr></thead><tbody>{(courses||[]).map((c:any)=><tr key={c.id}><td>{c.title}</td><td><span className="badge">{c.status}</span></td><td><form action={togglePublish}><input type="hidden" name="table" value="courses"/><input type="hidden" name="id" value={c.id}/><input type="hidden" name="status" value={c.status}/><button className="text-button" type="submit">{c.status==='published'?'Passar a rascunho':'Publicar'}</button></form></td></tr>)}</tbody></table></section>
 <section className="section card"><h2>Últimas aulas</h2><table className="table"><thead><tr><th>Aula</th><th>Legal</th><th>Estado</th><th></th></tr></thead><tbody>{(lessons||[]).map((l:any)=><tr key={l.id}><td>{l.title}</td><td>{l.legal_sensitive?(l.verified_at||'por verificar'):'—'}</td><td>{l.status}</td><td><form action={togglePublish}><input type="hidden" name="table" value="lessons"/><input type="hidden" name="id" value={l.id}/><input type="hidden" name="status" value={l.status}/><button className="text-button" type="submit">{l.status==='published'?'Despublicar':'Publicar'}</button></form></td></tr>)}</tbody></table></section>
 <section className="section card"><h2>Radar Legislativo</h2><table className="table"><thead><tr><th>Título</th><th>Verificado</th><th>Estado</th><th></th></tr></thead><tbody>{(updates||[]).map((u:any)=><tr key={u.id}><td><strong>{u.topic}</strong><br/>{u.title}</td><td>{u.verified_at}</td><td>{u.status}</td><td><form action={togglePublish}><input type="hidden" name="table" value="legislative_updates"/><input type="hidden" name="id" value={u.id}/><input type="hidden" name="status" value={u.status}/><button className="text-button" type="submit">{u.status==='published'?'Despublicar':'Publicar'}</button></form></td></tr>)}</tbody></table></section>
 </AppShell>
}
