import AppShell from '@/components/AppShell'
import AdminNav from '@/components/AdminNav'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { redirect } from 'next/navigation'
import { createCourse,createModule,createLesson,togglePublish,updateCourseMeta,updateModuleMeta,updateLessonMeta,markLessonForReview,verifyLessonToday } from '../actions'
import Link from 'next/link'

export default async function ContentAdmin({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const params=await searchParams;const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect('/login')
 const {data:p}=await s.from('profiles').select('role').eq('id',user.id).single();if(p?.role!=='admin')redirect('/dashboard')
 const a=createAdminClient()
 const [{data:courses},{data:modules},{data:lessons}]=await Promise.all([
   a.from('courses').select('id,title,slug,description,level,status,position').order('position'),
   a.from('modules').select('id,title,description,course_id,status,position').order('course_id').order('position'),
   a.from('lessons').select('id,title,module_id,status,duration_minutes,legal_sensitive,verified_at,source_url').order('module_id').order('position')
 ])
 const courseMap=new Map((courses||[]).map((x:any)=>[x.id,x]))
 const moduleMap=new Map((modules||[]).map((x:any)=>[x.id,x]))
 const displayLessons=params.review?(lessons||[]).filter((l:any)=>l.legal_sensitive&&!l.verified_at):(lessons||[])
 return <AppShell><div className="admin-head"><div><div className="eyebrow">ADMINISTRAÇÃO</div><h1>Conteúdos</h1><p className="muted">Cursos, módulos, aulas, publicação e revisão jurídica.</p></div></div><AdminNav/>
 <section className="section admin-grid"><div className="card"><h2>Novo curso</h2><form action={createCourse}><label className="field">Título<input name="title" required/></label><label className="field">Slug<input name="slug" required/></label><label className="field">Nível<input name="level" placeholder="Especialização"/></label><label className="field">Descrição<textarea name="description" rows={3}/></label><button className="btn">Criar rascunho</button></form></div>
 <div className="card"><h2>Novo módulo</h2><form action={createModule}><label className="field">Curso<select name="course_id">{(courses||[]).filter((c:any)=>c.status!=='archived').map((c:any)=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label className="field">Título<input name="title" required/></label><label className="field">Descrição<textarea name="description" rows={3}/></label><label className="field">Posição<input name="position" type="number" defaultValue={1}/></label><button className="btn">Criar módulo</button></form></div></section>
 <section className="section card"><div className="section-heading"><div><div className="eyebrow">FORMAÇÕES</div><h2>Gerir cursos</h2></div></div><div className="admin-edit-list">{(courses||[]).map((c:any)=><details key={c.id}><summary><div><strong>{c.title}</strong><span>{c.level} · {c.status}</span></div><span className="badge">{(modules||[]).filter((m:any)=>m.course_id===c.id).length} módulos</span></summary><div className="details-body"><form action={updateCourseMeta} className="admin-edit-grid"><input type="hidden" name="id" value={c.id}/><label className="field">Título<input name="title" defaultValue={c.title}/></label><label className="field">Nível<input name="level" defaultValue={c.level}/></label><label className="field wide">Descrição<textarea name="description" rows={2} defaultValue={c.description}/></label><button className="btn">Guardar</button></form><form action={togglePublish} className="inline-form"><input type="hidden" name="table" value="courses"/><input type="hidden" name="id" value={c.id}/><input type="hidden" name="status" value={c.status}/><button className="text-button">{c.status==='published'?'Passar a rascunho':'Publicar'}</button></form></div></details>)}</div></section>
 <section className="section card"><div className="section-heading"><div><div className="eyebrow">MÓDULOS</div><h2>Estrutura das formações</h2></div></div><div className="admin-edit-list">{(modules||[]).map((m:any)=><details key={m.id}><summary><div><strong>{m.title}</strong><span>{courseMap.get(m.course_id)?.title} · posição {m.position}</span></div><span className="badge">{m.status}</span></summary><div className="details-body"><form action={updateModuleMeta} className="admin-edit-grid"><input type="hidden" name="id" value={m.id}/><label className="field">Título<input name="title" defaultValue={m.title}/></label><label className="field">Posição<input name="position" type="number" defaultValue={m.position}/></label><label className="field wide">Descrição<textarea name="description" rows={2} defaultValue={m.description}/></label><button className="btn">Guardar</button></form><form action={togglePublish}><input type="hidden" name="table" value="modules"/><input type="hidden" name="id" value={m.id}/><input type="hidden" name="status" value={m.status}/><button className="text-button">{m.status==='published'?'Despublicar':'Publicar'}</button></form></div></details>)}</div></section>
 <section className="section card"><div className="section-heading"><div><div className="eyebrow">AULAS</div><h2>{params.review?'Conteúdo que necessita revisão':'Gerir aulas'}</h2></div>{params.review&&<Link className="quiet-link" href="/admin/conteudos">Mostrar todas</Link>}</div>
 <div className="admin-edit-list">{displayLessons.map((l:any)=><details key={l.id}><summary><div><strong>{l.title}</strong><span>{courseMap.get(moduleMap.get(l.module_id)?.course_id)?.title} · {moduleMap.get(l.module_id)?.title}</span></div><span className={l.legal_sensitive&&!l.verified_at?'badge badge-danger':'badge'}>{l.legal_sensitive?(l.verified_at||'Rever'):'Editorial'}</span></summary><div className="details-body"><form action={updateLessonMeta} className="admin-edit-grid"><input type="hidden" name="id" value={l.id}/><label className="field">Título<input name="title" defaultValue={l.title}/></label><label className="field">Duração<input name="duration_minutes" type="number" defaultValue={l.duration_minutes||8}/></label><label className="field wide">Fonte oficial<input name="source_url" type="url" defaultValue={l.source_url||''}/></label><label className="field">Verificado em<input name="verified_at" type="date" defaultValue={l.verified_at||''}/></label><button className="btn">Guardar</button></form><div className="actions-inline"><Link className="text-button" href={`/admin/conteudos/aula/${l.id}`}>Editar conteúdo</Link><form action={togglePublish}><input type="hidden" name="table" value="lessons"/><input type="hidden" name="id" value={l.id}/><input type="hidden" name="status" value={l.status}/><button className="text-button">{l.status==='published'?'Despublicar':'Publicar'}</button></form>{l.legal_sensitive&&<form action={l.verified_at?markLessonForReview:verifyLessonToday}><input type="hidden" name="id" value={l.id}/><button className="text-button">{l.verified_at?'Marcar para revisão':'Verificado hoje'}</button></form>}</div></div></details>)}</div></section>
 <section className="section card"><h2>Nova aula</h2><form action={createLesson} className="admin-edit-grid"><label className="field">Módulo<select name="module_id">{(modules||[]).map((m:any)=><option value={m.id} key={m.id}>{courseMap.get(m.course_id)?.title} · {m.title}</option>)}</select></label><label className="field">Título<input name="title" required/></label><label className="field">Slug<input name="slug" required/></label><label className="field">Duração<input type="number" name="duration_minutes" defaultValue={8}/></label><label className="field wide">Introdução<textarea name="intro" rows={3}/></label><label className="check-line"><input type="checkbox" name="legal_sensitive"/> Conteúdo sujeito a atualização</label><label className="field wide">Fonte oficial<input name="source_url" type="url"/></label><button className="btn">Criar aula</button></form></section>
 </AppShell>
}
