import AppShell from '@/components/AppShell'
import { createClient } from '@/lib/supabase/server'
import Link from 'next/link'
export default async function Dashboard(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();const {data:profile}=user?await supabase.from('profiles').select('full_name').eq('id',user.id).maybeSingle():{data:null}
 const {data:lessons}=await supabase.from('lessons').select('id').eq('status','published');const ids=(lessons||[]).map((x:any)=>x.id);let done=0;if(user&&ids.length){const {count}=await supabase.from('user_lesson_progress').select('*',{count:'exact',head:true}).eq('user_id',user.id).eq('completed',true).in('lesson_id',ids);done=count||0}const total=ids.length,pct=total?Math.round(done/total*100):0
 const {data:attempts}=user?await supabase.from('quiz_attempts').select('score').eq('user_id',user.id):{data:[] as any[]};const avg=attempts?.length?Math.round(attempts.reduce((s:any,a:any)=>s+Number(a.score),0)/attempts.length):0
 const {data:update}=await supabase.from('legislative_updates').select('title,topic,verified_at').eq('status','published').order('published_on',{ascending:false}).limit(1).maybeSingle()
 const name=profile?.full_name?.trim()||user?.email?.split('@')[0]||''
 return <AppShell><div className="topbar"><div><div className="eyebrow">Formação profissional</div><h1>Bom dia{name?`, ${name}`:''}.</h1><p className="muted">Continue a sua formação ou consulte ferramentas de trabalho.</p></div><span className="badge">Academia ativa</span></div><section className="section grid grid-3"><div className="card"><div className="muted">Progresso geral</div><div className="metric">{pct}%</div><div className="progress"><span style={{width:`${pct}%`}}/></div></div><div className="card"><div className="muted">Aulas concluídas</div><div className="metric">{done}</div><div className="muted">de {total} publicadas</div></div><div className="card"><div className="muted">Média nos testes</div><div className="metric">{avg?`${avg}%`:'—'}</div><div className="muted">{attempts?.length||0} tentativa(s)</div></div></section><section className="section grid grid-2"><div className="hero-card"><div className="brand-kicker">Continuar formação</div><h2 style={{marginTop:12}}>Nível 1 · Iniciante</h2><p>O percurso principal já é carregado dinamicamente a partir do Supabase.</p><Link className="btn secondary" href="/academia/iniciante">Abrir Academia →</Link></div><div className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12}}><h2>Radar Legislativo</h2><span className="badge">Atualizado</span></div>{update?<><p><strong>{update.topic}</strong> · {update.title}</p><div className="admin-note">Verificado em <strong>{update.verified_at}</strong></div><Link className="text-link" href="/radar">Ver atualização →</Link></>:<p className="muted">Ainda não existem atualizações publicadas.</p>}</div></section></AppShell>
}
